#!/bin/sh

muted=$(pacmd list-sinks | awk '/muted/ { print $2 }')
vol=$(pactl list sinks | awk '/Volume:/ {printf "%s ",$5}' | cut -f1 -d ' ' | cut -f1 -d '%')

if [ "$muted" = "no" ]; then
	if [ "$vol" -ge 65 ]; then
		echo "  $vol% "
	elif [ "$vol" -ge 40 ]; then
			echo "  $vol% "
	elif
	       [ "$vol" -ge 0 ]; then
	 		echo "  $vol% "		
	fi
else
	echo "  muted "
fi
